Repository bounswe/bounswe2019group9, pull requests merged in 2019-05, with the labels that each got.

#93 Practice app skeleton
  .gitignore
  .travis.yml
  LICENSE
  practice-app/LICENSE
  practice-app/README.md
  practice-app/appspec.yml
  practice-app/manage.py
  practice-app/polls/__init__.py
  practice-app/polls/admin.py
  practice-app/polls/apps.py
  practice-app/polls/migrations/0001_initial.py
  practice-app/polls/migrations/__init__.py
  practice-app/polls/models.py
  practice-app/polls/static/polls/images/background.gif
  practice-app/polls/static/polls/style.css
  practice-app/polls/templates/polls/detail.html
  practice-app/polls/templates/polls/index.html
  practice-app/polls/templates/polls/results.html
  practice-app/polls/tests.py
  practice-app/polls/urls.py
  practice-app/polls/views.py
  practice-app/practice_app/__init__.py
  practice-app/practice_app/base_settings.py
  practice-app/practice_app/prod_settings.py
  practice-app/practice_app/settings.py
  practice-app/practice_app/urls.py
  practice-app/practice_app/wsgi.py
  practice-app/prod_requirements.txt
  practice-app/requirements.txt
  practice-app/scripts/fix_permissions.sh
  practice-app/scripts/install_os_dependencies.sh
  practice-app/scripts/install_python_dependencies.sh
  practice-app/scripts/restart_application.sh
  practice-app/scripts/start_application.sh
  practice-app/scripts/stop_application.sh
  practice-app/uwsgi-conf.ini
Labels: urgency : emergent

#97 Travis deploy fix
  .travis.yml
Labels: urgency : emergent

#99 Translation feature
  practice-app/practice_app/base_settings.py
  practice-app/practice_app/urls.py
  practice-app/translate/__init__.py
  practice-app/translate/admin.py
  practice-app/translate/apps.py
  practice-app/translate/docs/API-Documentation.md
  practice-app/translate/migrations/0001_initial.py
  practice-app/translate/migrations/__init__.py
  practice-app/translate/models.py
  practice-app/translate/serializers.py
  practice-app/translate/static/translate/style.css
  practice-app/translate/templates/translate/translator.html
  practice-app/translate/tests.py
  practice-app/translate/urls.py
  practice-app/translate/views.py
Labels: urgency : high

#114 add __init__.py to module folder
  practice-app/texttospeech/__init__.py
Labels: urgency : emergent

#113 Updated movie recommendation
  .gitignore
  myvenv/bin/activate
  myvenv/bin/activate.csh
  myvenv/bin/activate.fish
  myvenv/bin/chardetect
  myvenv/bin/django-admin
  myvenv/bin/django-admin.py
  myvenv/bin/easy_install
  myvenv/bin/easy_install-3.5
  myvenv/bin/pip
  myvenv/bin/pip3
  myvenv/bin/pip3.5
  myvenv/bin/python
  myvenv/bin/python3
  myvenv/bin/sqlformat
  myvenv/lib64
  myvenv/pip-selfcheck.json
  myvenv/pyvenv.cfg
  myvenv/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl
  myvenv/share/python-wheels/chardet-2.3.0-py2.py3-none-any.whl
  myvenv/share/python-wheels/colorama-0.3.7-py2.py3-none-any.whl
  myvenv/share/python-wheels/distlib-0.2.2-py2.py3-none-any.whl
  myvenv/share/python-wheels/html5lib-0.999-py2.py3-none-any.whl
  myvenv/share/python-wheels/ipaddress-0.0.0-py2.py3-none-any.whl
  myvenv/share/python-wheels/lockfile-0.12.2-py2.py3-none-any.whl
  myvenv/share/python-wheels/packaging-16.6-py2.py3-none-any.whl
  myvenv/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl
  myvenv/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl
  myvenv/share/python-wheels/progress-1.2-py2.py3-none-any.whl
  myvenv/share/python-wheels/pyparsing-2.0.3-py2.py3-none-any.whl
  myvenv/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl
  myvenv/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl
  myvenv/share/python-wheels/setuptools-20.7.0-py2.py3-none-any.whl
  myvenv/share/python-wheels/six-1.10.0-py2.py3-none-any.whl
  myvenv/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl
  myvenv/share/python-wheels/wheel-0.29.0-py2.py3-none-any.whl
  practice-app/arda/tests.py
  practice-app/arda/views.py
  practice-app/home/views.py
  practice-app/speech.wav
Labels: urgency : emergent

#116 TEMP FILE NAMED SPEECH.WAV SHALL NOT BE PUT ON REPO
  .gitignore
  practice-app/speech.wav
Labels: urgency : emergent

#115 Prediction from given IP or IP of Requester
  practice-app/burhan/__init__.py
  practice-app/burhan/admin.py
  practice-app/burhan/apps.py
  practice-app/burhan/doc.md
  practice-app/burhan/migrations/__init__.py
  practice-app/burhan/models.py
  practice-app/burhan/tests.py
  practice-app/burhan/urls.py
  practice-app/burhan/views.py
  practice-app/home/views.py
  practice-app/practice_app/base_settings.py
  practice-app/practice_app/urls.py
Labels: workflow: 4-In Review
